### ISSUE TITLE
Logic jumps don't seem to be working

### ISSUE THREAD

**Issue by fhinson** [leemachin/ask_awesomely#16]
I've been attempting to integrate logic jumps into my form. To test, I implemented some code you provided in an rspec:

```
  jump from: :shall_continue?, to: :shall_not_continue, if_answer: false

  field :yes_no do
    ask "Shall we continue?"
    ref :shall_continue?
  end

  field :statement do
    say "Thanks!"
  end

  field :statement do
    say "Wut?"
    ref :shall_not_continue
  end
```

When I build my typeform, it doesn't create a public url or id. 

`!ruby/object:OpenStruct table: :title: Auto Application :fields: - !ruby/object:AskAwesomely::Field::YesNo state: !ruby/object:OpenStruct table: :type: :yes_no :question: Shall we continue? :ref: shall_continue? modifiable: true - !ruby/object:AskAwesomely::Field::Statement state: !ruby/object:OpenStruct table: :type: :statement :question: Thanks! modifiable: true - !ruby/object:AskAwesomely::Field::Statement state: !ruby/object:OpenStruct table: :type: :statement :question: Wut? :ref: shall_not_continue modifiable: true :branding: false :design_id: !ruby/object:Proc {} :jumps: - !ruby/object:AskAwesomely::LogicJump state: !ruby/object:OpenStruct table: :to: :shall_not_continue :from: :shall_continue? :if_answer: false modifiable: true links: id:`

When I remove the line `jump from: :shall_continue?, to: :shall_not_continue, if_answer: false` it still fails.

Only after I also remove the `ref` statements does it build the typeform correctly. I suspect this is some sort of bug with both the `jump` and `ref` methods.

**Comment by leemachin** [comment]
Another silly mistake (with wrong tests to back it up...) on my part. This is fixed now.

**Comment by fhinson** [comment]
@leemachin Upgraded, but i'm still experiencing the same issue

**Comment by leemachin** [comment]
My bad, I forgot to change another part. Another release with a fix made.

**Comment by fhinson** [comment]
Working great! Thanks for the help.
